<a href="https://colab.research.google.com/github/utkarsh5547v-sys/class_no_5/blob/main/C_n_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv("session4_dummy_students_data.csv.xls")

In [ ]:
df['average'] = df[['math', 'science', 'english']].mean(axis=1)
display(df.head())

,student_id,name,age,city,math,science,english,attendance_percent,study_hours_per_week,assignments_submitted,final_project_score,average
0,101,Aarav,16,Mumbai,78,84,69,92,8,9,82,77.000000
1,102,Diya,16,Delhi,91,88,94,96,11,10,93,91.000000
2,103,Kabir,17,Mathura,55,61,58,75,5,6,60,58.000000
3,104,Meera,16,Noida,72,79,81,89,7,8,78,77.333333
4,105,Rohan,17,Mumbai,40,52,47,68,3,5,45,46.333333

In [ ]:
df['result'] = df['average'].apply(lambda x: 'Pass' if x >= 40 else 'Fail')
display(df.head())

,student_id,name,age,city,math,science,english,attendance_percent,study_hours_per_week,assignments_submitted,final_project_score,average,result
0,101,Aarav,16,Mumbai,78,84,69,92,8,9,82,77.000000,Pass
1,102,Diya,16,Delhi,91,88,94,96,11,10,93,91.000000,Pass
2,103,Kabir,17,Mathura,55,61,58,75,5,6,60,58.000000,Pass
3,104,Meera,16,Noida,72,79,81,89,7,8,78,77.333333,Pass
4,105,Rohan,17,Mumbai,40,52,47,68,3,5,45,46.333333,Pass

In [ ]:
class_average = df['average'].mean()
print(f"Class Average: {class_average:.2f}")

Class Average: 71.35

In [ ]:
highest_average = df['average'].max()
lowest_average = df['average'].min()

print(f"Highest Average: {highest_average:.2f}")
print(f"Lowest Average: {lowest_average:.2f}")

Highest Average: 92.67
Lowest Average: 40.67

In [ ]:
highest_average_score = df['average'].max()
top_students = df[df['average'] == highest_average_score][['name', 'average']]

print("Top student(s):")
display(top_students)

Top student(s):

    name    average
15  Riya  92.666667

In [ ]:
students_low_attendance = df[df['attendance_percent'] < 75][['name', 'attendance_percent']]

print("Students with attendance below 75:")
display(students_low_attendance)

Students with attendance below 75:

      name  attendance_percent
4    Rohan                  68
8   Vivaan                  71
12     Dev                  62
18    Yash                  66

In [ ]:
students_few_assignments = df[df['assignments_submitted'] < 6][['name', 'assignments_submitted']]

print("Students who submitted fewer than 6 assignments:")
display(students_few_assignments)

Students who submitted fewer than 6 assignments:

     name  assignments_submitted
4   Rohan                      5
12    Dev                      4
18   Yash                      5

In [ ]:
df.to_csv('session4_student_report.csv', index=False)
print("Final report saved to 'session4_student_report.csv'")

Final report saved to 'session4_student_report.csv'

In [ ]:
df.columns

Index(['student_id', 'name', 'age', 'city', 'math', 'science', 'english',
       'attendance_percent', 'study_hours_per_week', 'assignments_submitted',
       'final_project_score', 'average', 'result'],
      dtype='object')